stages:
  - build

include:
  - project: 'tools/templates'
    ref: main
    file: '/ci_registry.yml'

variables:
  DIND: registry.bukatch.uk/docker/dind:27.2.1

before_script:
  - unset DOCKER_HOST
  - !reference [.registry]

kamikaze:
  stage: build
  image: ${DIND}
  services:
    - name: ${DIND}
  script:
    - exit 0
  when: always